### ISSUE TITLE
User Documentation/Quick Start

### ISSUE THREAD

**Issue by henfri** [cyborgbackup/cyborgbackup#35]
Hello,

I find the documentation under https://cyborgbackup.readthedocs.io/en/latest/user/quickstart.html# quite odd, to be honest. 
That is not a Quick Start, but a look deep into the engine room.
Is there a User-Documentation? 
I already fail getting something similar to the screenshots https://cyborgbackup.readthedocs.io/en/latest/user/screenshots.html.
When accessing host:8000 I only get the status page (System Status)

Greetings,
Hendrik

**Comment by GaetanF** [comment]
Hello,

I haven't finish the documentation yet.
The UI have been spliced in another project part to simplify the development.

You can launch the UI using the following docker run command : 
`docker run -p 8888:80 cyborgbackup/cyborgbackup-ui:develop`

Regards

**Comment by henfri** [comment]
Hello,

I am not complaining ;-) 
Just giving feedback, hoping that it is useful when you work on the documentation.

I will try the UI.
I have seen an issue though:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2020-10-04 11:32:02.840 UTC [1] FATAL:  database files are incompatible with server
2020-10-04 11:32:02.840 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2020-10-04 11:59:52.185 UTC [1] FATAL:  database files are incompatible with server
2020-10-04 11:59:52.185 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1).    
```

Would I have had to configure volumes?
```
volumes:
  postgres_data:
  esdata:
```
Then, a template would be good on the docker-compose.yml

Regards,
Hendrik

**Comment by GaetanF** [comment]
It seems you already have a postgres_data volume with a previous PostgreSQL Engine.

You can force the postgres docker image version on the docker-compose.yml file or remove the volume (they will erase all data from CyBorgBackup)

**Comment by henfri** [comment]
Hello,

thanks, that helped. 
But I cannot log in (the button just turns grey).
It may be related to the celery container not running:

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 55, in stop
    ignore_errors(c, c.task_consumer.cancel)
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 298, in ignore_errors
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 488, in cancel
    cancel(tag)
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 1440, in basic_cancel
    wait=None if nowait else spec.Basic.CancelOk,
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 68, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 79, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 521, in on_inbound_method
    method_sig, payload, content,
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 1615, in _on_basic_deliver

    fun(msg)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 567, in on_task_received
    callbacks,
  File "/usr/local/lib/python3.6/site-packages/celery/worker/strategy.py", line 157, in task_message_handler
    if (req.expires or req.id in revoked_tasks) and req.revoked():
  File "/usr/local/lib/python3.6/site-packages/celery/worker/request.py", line 280, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "/usr/local/lib/python3.6/site-packages/celery/worker/request.py", line 263, in _announce_revoked
    self.id, reason, request=self, store_result=self.store_errors,
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 191, in mark_as_revoked
    traceback=None, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 322, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 29, in _store_result
    meta=meta,
  File "/usr/local/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_celery_results/managers.py", line 119, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_celery_results_taskresult" does not exist
LINE 1: ...", "django_celery_results_taskresult"."meta" FROM "django_ce...
[2020-10-04 12:11:30,469: WARNING/MainProcess] Received method (60, 31) during closing channel 3. This method will be ignored
```

Regards,
Hendrik
