### ISSUE TITLE
[IDEA] container web has to be restarted a 2nd time after restarting the project

### ISSUE THREAD

**Issue by fldu** [cyborgbackup/cyborgbackup#45]
Hello,

web container is breaking when you start the project, restart it. It is mainly due to the fact that postgreSQL DB is not ready to receive connections. A manual restart of web container is required:

```bash
docker-compose logs web
```
ouput:
```
Attaching to cyborgbackup_web_1
web_1                | Traceback (most recent call last):
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1                |     self.connect()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
web_1                |     self.connection = self.get_new_connection(conn_params)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1                |     connection = Database.connect(**conn_params)
web_1                |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
web_1                |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1                | psycopg2.OperationalError: could not connect to server: Connection refused
web_1                |  Is the server running on host "postgres" (172.24.0.2) and accepting
web_1                |  TCP/IP connections on port 5432?
web_1                | The above exception was the direct cause of the following exception:
web_1                | Traceback (most recent call last):
web_1                |   File "/cyborgbackup/manage.py", line 22, in <module>
web_1                |     execute_from_command_line(sys.argv)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
web_1                |     utility.execute()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
web_1                |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
web_1                |     self.execute(*args, **cmd_options)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
web_1                |     output = self.handle(*args, **options)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
web_1                |     res = handle_func(*args, **kwargs)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
web_1                |     executor = MigrationExecutor(connection, self.migration_progress_callback)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1                |     self.loader = MigrationLoader(self.connection)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
web_1                |     self.build_graph()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
web_1                |     self.applied_migrations = recorder.applied_migrations()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
web_1                |     if self.has_table():
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
web_1                |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
web_1                |     return self._cursor()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
web_1                |     self.ensure_connection()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1                |     self.connect()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
web_1                |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1                |     self.connect()
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
web_1                |     self.connection = self.get_new_connection(conn_params)
web_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1                |     connection = Database.connect(**conn_params)
web_1                |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
web_1                |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1                | django.db.utils.OperationalError: could not connect to server: Connection refused
web_1                |  Is the server running on host "postgres" (172.24.0.2) and accepting
web_1                |  TCP/IP connections on port 5432?

```

In [docker-compose.yml](https://github.com/cyborgbackup/cyborgbackup/blob/master/docker-compose.yml)
```
  web:
    image: cyborgbackup/cyborgbackup:latest
    command: bash -c "python /cyborgbackup/manage.py migrate --noinput && python /cyborgbackup/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
```

could be modified to :
```
  web:
    image: cyborgbackup/cyborgbackup:latest
    command: bash -c "python /cyborgbackup/manage.py migrate --noinput && python /cyborgbackup/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

```

Thanks for this awesome project
Regards

**Comment by GaetanF** [comment]
Hello,

Indeed. I will add them in the develop branch.

Regards

**Comment by GaetanF** [comment]
The restart parameter have been integrated in the docker-compose file.

Thanks
Regards
