### ISSUE TITLE
Docker Compose Installation:  The celery contain is encountering a critical error and then exiting

### ISSUE THREAD

**Issue by morsedl** [cyborgbackup/cyborgbackup#93]
Hi,

As I've mentioned in a number of recent posts, I am trying to get Cyborg Backup (CB) working correctly via the published `docker-compose` installation. In particular, issue #79 is significant obstacle for us in deploying CB.

Normally I would post the following under issue #79, but at this point it I cannot be certain the error messages I'm reporting below are indeed related to / relevant for that issue. 

The following is the relevant output of the logs for the `celery` container.

There seems to be a critical error (line 3, below) having to do with a PRECONDITION on some channel 1.  After this occurs, the `celery` container exits (stops) and stays exited (stopped).

I understand the error, but am too unfamiliar with CB internals to know how to help correct this problem.

Not that it's likely needed, but for completeness I have included also the state of our Docker containers (i.e., the output of `docker ps -a`) at the very end of this post, after the following stack trace.

STACK TRACE FROM `celery` CONTAINER LOGS

```
2024-06-06 12:30:00,110 DEBUG    cyborgbackup.main.utils.expect {'BORG_PASSPHRASE': 'XXXXXX', 'BORG_REPO': 'prxy@backup:repo', 'BORG_RELOCATED_REPO_ACCESS_IS_OK': 'yes', 'BORG_RSH': 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'}
[2024-06-06 12:30:00,110: DEBUG/ForkPoolWorker-1] {'BORG_PASSPHRASE': 'Rar0ig2ooc8B', 'BORG_REPO': 'prxy@backup:repo', 'BORG_RELOCATED_REPO_ACCESS_IS_OK': 'yes', 'BORG_RSH': 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'}
[2024-06-06 13:01:08,154: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 521, in on_inbound_method
    method_sig, payload, content,
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 280, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
[2024-06-06 13:01:08,257: ERROR/MainProcess] Error on stopping Pool: TypeError("can't pickle _thread.lock objects")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 521, in on_inbound_method
    method_sig, payload, content,
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 280, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 373, in stop
    return self.obj.stop()
  File "/usr/local/lib/python3.7/site-packages/celery/concurrency/base.py", line 122, in stop
    self.on_stop()
  File "/usr/local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 140, in on_stop
    self._pool.join()
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1578, in join
    stop_if_not_current(self._result_handler)
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 143, in stop_if_not_current
    thread.stop(timeout)
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 500, in stop
    self.on_stop_not_started()
  File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 332, in on_stop_not_started
    check_timeouts()
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 744, in handle_event
    next(self._it)
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 697, in handle_timeouts
    cache = copy.deepcopy(self.cache)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
```

STATUS OF DOCKER CONTAINERS AFTER THIS CRITICAL ERROR

```
root@backup:/opt/lfg# docker ps -a
CONTAINER ID   IMAGE                                  COMMAND                  CREATED       STATUS                      PORTS                                                                                                                                                 NAMES
629edd2ff226   cyborgbackup/cyborgbackup-ui:develop   "/docker-entrypoint.…"   4 hours ago   Up 4 hours                  0.0.0.0:4001->80/tcp, :::4001->80/tcp                                                                                                                 lfg_ui_1
bbd0058b8ba6   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   4 hours ago   Up 4 hours                  8000/tcp                                                                                                                                              lfg_callback_receiver_1
4b7b16e0085a   cyborgbackup/cyborgbackup:latest       "celery -A cyborgbac…"   4 hours ago   Up 4 hours                  8000/tcp                                                                                                                                              lfg_celery_beat_1
29695c9ec859   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   4 hours ago   Up 4 hours                  0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                             lfg_api_1
9c0c96711bff   cyborgbackup/cyborgbackup:latest       "celery -A cyborgbac…"   4 hours ago   Exited (1) 54 minutes ago                                                                                                                                                         lfg_celery_1
07d8b7a45f28   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   4 hours ago   Up 4 hours                  8000/tcp                                                                                                                                              lfg_channel_workers_1
187f43e49825   rabbitmq:management                    "docker-entrypoint.s…"   4 hours ago   Up 4 hours                  4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   lfg_rabbitmq_1
99ba51c7e8c5   mongo:bionic                           "docker-entrypoint.s…"   4 hours ago   Up 4 hours                  0.0.0.0:27017->27017/tcp, :::27017->27017/tcp                                                                                                         lfg_mongodb_1
6e48e63d5fbf   postgres:latest                        "docker-entrypoint.s…"   4 hours ago   Up 4 hours                  0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                                             lfg_postgres_1
```

(Note that our configuration of containers is exactly per the docker-compose install instructions, but that we server the UI on port 4001 rather than the default port 8000.)

**Comment by GaetanF** [comment]
Hello,

Could you try with the latest cyborgbackup image and docker-compose file ?

Regards

**Comment by morsedl** [comment]
Hi,Sure thing. Thanks for this and your other replies over the weekend regarding this and other issues I recently created on GitHub.I should be able to try things out within the next 4 to 6 hours and get back with you. I assume I just need to do a `docker-compose pull` and the let compose recreate the containers. But to be certain, I’ll also re-retrieve the `docker-compose.xml`itself and check for any changes there as well. I’ll also empty the data volume folders so that everything gets re-created from scratch.DougVon meinem iPhone gesendetAm 10.06.2024 um 10:21 schrieb Gaetan Ferez ***@***.***>:﻿
Hello,
Could you try with the latest cyborgbackup image and docker-compose file ?
Regards

**Comment by morsedl** [comment]
@GaetanF Well, things did not work out too well. But I do suspect that perhaps many of the fixes are straightforward.

Before anything, I performed a `docker-compose pull` with my existing `docker-compose.yml` file in place. This caused all docker images to be updated (the only thing we have on Docker on this host, `backup`, is Cyborg Backup, CB). Thus, I can confirm that all of the CB-containers updated.

I then put the newest version of the published `docker-compose.yml` file in place and again performed `docker-compose pull`, which resulted in nothing new being pulled. The new `docker-compose.yml` file does seem a good bit different, mostly in that some sections have been re-arranged, and many `command:` sections appear different.

Starting things up with `docker-compose up -d` resulted in all of the containers starting, but then four of them exiting.

`mongodb` was among them and since I knew most essential for operations, I inspected the `mongodb` container logs first and saw an error about upgrading some document type. Since I had no need to preserve any existing data, I then just shutdown everything with `docker-compose down`, deleted the `postgres` and `mongodb` data directories I had previously created and then just created new, empty ones.

Thus, at this point then, we're talking about an entirely new, fresh installation attempt.

I should also briefly note that we do not use Docker data volumes. Thus, the data for `monogodb` and `postgres` in our case resides directly alongside the `docker-compose.yml` file under subdirectories `mongodb/data` and `postgres/data`, repectively.  We also do not use the default port of `8088` for the accessing the `ui` container but rather port `4001`.

These are minor differences, and at the end of the console output I share below, I verify using `diff` that `docker-compose.yml` file we're working with is the same as the one presently available for download, excepting the three changes just noted.

This attempt with the latest of everything and no pre-existing data also did not work out well. Three containers, as with the last attempt, exited rather quickly, and the `api` container appears to be in a restart loop. The `mongodb` container this time however did stay up.

Below are the results immediately after `docker-compose up -d` as well as the results of some of my initial investigations.

In summary, it seems that things have gone a bit more-sideways with this recent round of updates, not less. On the other hand, best can tell, the problem with the `api` container may just be an incorrect, out-of-date, or missing Python library, and it seems the exiting of the three other containers is just the initial calls for their initialization procedure / processes have become incorrect.

I'll dig deeper here as soon as I can (it might not be today) and report back. For now I just wanted to report my initial findings.

```
root@backup:/opt/lfg# docker ps -a
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                          PORTS                                                                                                                                                 NAMES
4e87abec2d32   cyborgbackup/cyborgbackup-ui:develop   "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes                    0.0.0.0:4001->80/tcp, :::4001->80/tcp                                                                                                                 lfg_ui_1
87a09e43dcac   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   7 minutes ago   Exited (2) 7 minutes ago                                                                                                                                                              lfg_callback_receiver_1
b435128bf70a   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   7 minutes ago   Exited (2) 7 minutes ago                                                                                                                                                              lfg_channel_workers_1
3686374b1f78   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   7 minutes ago   Restarting (2) 51 seconds ago                                                                                                                                                         lfg_api_1
6a2038b32d3c   cyborgbackup/cyborgbackup:latest       "celery -A cyborgbac…"   7 minutes ago   Exited (1) 7 minutes ago                                                                                                                                                              lfg_celery_beat_1
282f28a4e47f   cyborgbackup/cyborgbackup:latest       "celery -A cyborgbac…"   7 minutes ago   Up 7 minutes                    8000/tcp                                                                                                                                              lfg_celery_1
d04551e825b9   mongo:bionic                           "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                    0.0.0.0:27017->27017/tcp, :::27017->27017/tcp                                                                                                         lfg_mongodb_1
bac841a1956e   postgres:latest                        "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                    0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                                             lfg_postgres_1
153650a0ac32   rabbitmq:management                    "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                    4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   lfg_rabbitmq_1
root@backup:/opt/lfg# docker-compose logs callback_receiver | tail -20
Attaching to lfg_callback_receiver_1
callback_receiver_1  | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
root@backup:/opt/lfg# docker-compose logs channel_workers | tail -20
Attaching to lfg_channel_workers_1
channel_workers_1    | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
root@backup:/opt/lfg# docker-compose logs celery_beat | tail -20
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,605: WARNING/MainProcess] ^
celery_beat_1        | [2024-06-10 13:32:43,606: WARNING/MainProcess] _gdbm
celery_beat_1        | [2024-06-10 13:32:43,606: WARNING/MainProcess] .
celery_beat_1        | [2024-06-10 13:32:43,606: WARNING/MainProcess] error
celery_beat_1        | [2024-06-10 13:32:43,606: WARNING/MainProcess] :
celery_beat_1        | [2024-06-10 13:32:43,606: WARNING/MainProcess] [Errno 2] No such file or directory: '/usr/local/lib/python3.12/site-packages/var/run/celerybeat-schedule'
root@backup:/opt/lfg# docker-compose logs api | tail -20
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
api_1                | python: can't open file '/cyborgbackup/manage.py': [Errno 2] No such file or directory
root@backup:/opt/lfg# date
Mon Jun 10 08:44:04 CDT 2024
root@backup:/opt/lfg# docker-compose pull
Pulling postgres          ... done
Pulling redis             ... done
Pulling callback_receiver ... done
Pulling channel_workers   ... done
Pulling api               ... done
Pulling celery            ... done
Pulling celery_beat       ... done
Pulling mongodb           ... done
Pulling ui                ... done
root@backup:/opt/lfg# diff docker-compose-new.yml docker-compose-new-DIST.yml
7,8c7
<       # - postgres_data:/var/lib/postgresql/data/
<       - /opt/lfg/postgres/data:/var/lib/postgresql/data/
---
>       - postgres_data:/var/lib/postgresql/data/
63,64c62
<       # - mongo_data:/data/db
<       - /opt/lfg/mongodb/data:/data/db
---
>       - mongo_data:/data/db
72c70
<       - "4001:80"
---
>       - "8088:80"
73a72,74
> volumes:
>   postgres_data:
>   mongo_data:
root@backup:/opt/lfg# l
total 20
-rw-r--r-- 1 root root 1673 Jun  6 04:51 docker-compose-cur.yml
-rw-r--r-- 1 root root 1465 Jun 10 08:35 docker-compose-new-DIST.yml
-rw-r--r-- 1 root root 1525 Jun 10 08:23 docker-compose-new.yml
lrwxrwxrwx 1 root root   22 Jun 10 08:34 docker-compose.yml -> docker-compose-new.yml
drwxr-xr-x 3 root root 4096 Jun 10 08:31 mongodb
drwxr-xr-x 3 root root 4096 Jun 10 08:31 postgres
root@backup:/opt/lfg# 
```

**Comment by GaetanF** [comment]
Hello,

The docker-compose file have also been updated on my commits.
I now use a script file to prepare CyBorgBackup before start them instead of copy/paste command to create user. And I have fix the celery beat folder issue.

Could you update them ?

You will have an error in the logs about collectstatic permission denied on folder but they will not prevent CyBorgBackup to be usable.

Regards

**Comment by morsedl** [comment]
Well, I could swear I posted this yesterday, but it’s not showing up here, so here goes again.

First, my apologies for the slow response, I was rather ill earlier this week.

I re-retrieved the `docker-compose.yml`file and completely reset docker on the host with `docker system prune -a`. All of the container started and continued to run except `channel-workers`, which exited with the errors I’ve included below (i.e., the output of `docker-compose logs channel-workers`),

It looks like the `channel-workers` container is trying to connect to redis within itself (i.e., port `6379` on IP `127.0.0.1`). I try adding a `REDIS_URL=redis://redis:6379` line to my `.env` file, but that affected no change. I also started a shell within the `channel-workers` container and found no filenames containing the string “redis” within the in-container `/etc` directory (e.g., no `/etc/redis.conf` file).

So at this point I am not entirely sure how to proceed, nor is my confidence high that I’ve diagnosed the problem correctly.

```
root@backup:/opt/lfg# docker-compose up -d
Creating network "lfg_default" with the default driver
Creating lfg_redis_1    ... done
Creating lfg_mongodb_1  ... done
Creating lfg_postgres_1 ... done
Creating lfg_api_1               ... done
Creating lfg_channel_workers_1   ... done
Creating lfg_celery_1            ... done
Creating lfg_celery_beat_1       ... done
Creating lfg_callback_receiver_1 ... done
Creating lfg_ui_1                ... done
root@backup:/opt/lfg# docker-compose logs channel_workers 
Attaching to lfg_channel_workers_1
channel_workers_1    | 2024-06-14 07:05:25,306 INFO     django.channels.worker Running worker for channels ['websocket']
channel_workers_1    | 2024-06-14 07:05:25,306 INFO     django.channels.worker Running worker for channels ['websocket']
channel_workers_1    | Traceback (most recent call last):
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 274, in connect
channel_workers_1    |     await self.retry.call_with_retry(
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
channel_workers_1    |     return await do()
channel_workers_1    |            ^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 681, in _connect
channel_workers_1    |     reader, writer = await asyncio.open_connection(
channel_workers_1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/streams.py", line 48, in open_connection
channel_workers_1    |     transport, _ = await loop.create_connection(
channel_workers_1    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
channel_workers_1    |     raise exceptions[0]
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
channel_workers_1    |     sock = await self._connect_sock(
channel_workers_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
channel_workers_1    |     await self.sock_connect(sock, address)
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
channel_workers_1    |     return await fut
channel_workers_1    |            ^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
channel_workers_1    |     raise OSError(err, f'Connect call failed {address}')
channel_workers_1    | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)
channel_workers_1    | 
channel_workers_1    | During handling of the above exception, another exception occurred:
channel_workers_1    | 
channel_workers_1    | Traceback (most recent call last):
channel_workers_1    |   File "/usr/local/bin/cyborgbackup-manage", line 8, in <module>
channel_workers_1    |     sys.exit(manage())
channel_workers_1    |              ^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/cyborgbackup/__init__.py", line 91, in manage
channel_workers_1    |     execute_from_command_line(sys.argv)
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
channel_workers_1    |     utility.execute()
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
channel_workers_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
channel_workers_1    |     self.execute(*args, **cmd_options)
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
channel_workers_1    |     output = self.handle(*args, **options)
channel_workers_1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/channels/management/commands/runworker.py", line 45, in handle
channel_workers_1    |     worker.run()
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/asgiref/server.py", line 62, in run
channel_workers_1    |     event_loop.run_until_complete(self.handle())
channel_workers_1    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
channel_workers_1    |     return future.result()
channel_workers_1    |            ^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/channels/worker.py", line 30, in handle
channel_workers_1    |     [listener.result() for listener in listeners]
channel_workers_1    |      ^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/channels/worker.py", line 37, in listener
channel_workers_1    |     message = await self.channel_layer.receive(channel)
channel_workers_1    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/channels_redis/core.py", line 386, in receive
channel_workers_1    |     return (await self.receive_single(channel))[1]
channel_workers_1    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/channels_redis/core.py", line 408, in receive_single
channel_workers_1    |     content = await self._brpop_with_clean(
channel_workers_1    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/channels_redis/core.py", line 244, in _brpop_with_clean
channel_workers_1    |     await connection.eval(cleanup_script, 0, channel, backup_queue)
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/client.py", line 607, in execute_command
channel_workers_1    |     conn = self.connection or await pool.get_connection(command_name, **options)
channel_workers_1    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 1083, in get_connection
channel_workers_1    |     await self.ensure_connection(connection)
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 1116, in ensure_connection
channel_workers_1    |     await connection.connect()
channel_workers_1    |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 282, in connect
channel_workers_1    |     raise ConnectionError(self._error_message(e))
channel_workers_1    | redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. 111.
root@backup:/opt/lfg#
```
